redis:
  image: redis
  restart: always
  volumes:
    - ./persistent-data/redis:/data

database:
  image: mariadb
  restart: always
  volumes:
    - ./persistent-data/mariadb:/var/lib/mysql
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: "emdr-password"
    MYSQL_DATABASE: "eve"

processor:
  build: processor-node
  links:
    - redis
    - database
  ports:
    - "3000:3000"
  volumes:
    - ..:/root/emdr-process
  environment:
    NODE_PATH: /usr/local/lib/node_modules/

web:
  build: django-dev
  links:
    - database
  ports:
    - "31337:31337"
  volumes:
    - ..:/root/emdr-process
